---
locale: es
tags: []
layout: input_kids
editor: custom
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
name: El que quiera celeste, que mezcle azul y blanco
